# 服务设置
server:
  port: 8080 # 端口
  servlet:
    jsp:
      init-parameters:
        development: true # 开启JSP调试模式，修改JSP无需重启
# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/0617?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/page # 页面前缀

# Mybatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml # Mapper XML 扫包路径
  type-aliases-package: com.dj.ssm.pojo # 类别名
  configuration:
    map-underscore-to-camel-case: true
